name: Create Release Candidate
on:
  create:
    branches:
      - refs/heads/rel*

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Check for Existing Tag
        run: |
          tag_name=$(echo "${CI_COMMIT_REF_NAME}")
          if git tag -l | grep -q "${tag_name}"; then
            echo "Deleting existing tag ${tag_name}"
            git tag -d "${tag_name}"
          fi

      - name: Push Tag
        run: |
          tag_name=$(echo "${CI_COMMIT_REF_NAME}")
          if [ -n "${tag_name}" ]; then
            git tag "${tag_name}"
            git push origin --tags
          fi
