name: Create Tag on Release Branch

on:
  create:
    branches:
      - "*Rel*"
    branches-from:
      - "master"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          
      - name: Create Tag
        # You may pin to the exact commit or the version.
        # uses: negz/create-tag@39bae1e0932567a58c20dea5a1a0d18358503320
        uses: negz/create-tag@v1
        with:
          # Github Token
          token: ${{ secrets.RELEASE_TOKEN }}
          # Version (e.g. v0.1.0)
          version: v.0.0-${{ github.ref_name }}-RC
          # Tag message
          message: "This is the start of a release candidate called ${{ github.ref_name }}-RC tag"
          
 
        
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}"
          
          
