name: Create Release Branch and Tag
on:
  create:
    branches:
      - refs/heads/Rel*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
      - name: Check Tag Name
        run: |
          tag_name=$(echo "${GITHUB_REF}" | sed -e "s|refs/heads/||")
          if git tag -l | grep -q "${tag_name}"; then
            echo "Tag already exists, deleting branch"
            git branch -D "${tag_name}"
          else
            echo "Creating branch"
            git checkout -b "${tag_name}"
          fi
      - name: Create Git Tag
        run: |
          git tag "${tag_name}"
