name: Create Tag on Release Branch

on:
  push:
    branches:
      - "*Rel*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v2
        with:
          ref: ${{ github.ref }}
          
      - name: Create Tag
      - run: git config --global user.email "jt-atkins@hotmail.com"
      - run: git config --global user.name "jt-atkins"
      - run: |
          git tag -a ${{ github.ref }}-RC -m "Release tag"
          git push origin ${{ github.ref }}
          
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}-RC"
