name: Create Tag on Release Branch

on:
  push:
    branches:
      - "*Rel*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Tag
        run: |
          git tag -a ${{ github.ref }} -m "Release tag"
          git push origin ${{ github.ref }}
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}"
