name: Create Tag on Release Branch

on:
  create:
    branches:
      - "*Rel*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          
      - name: Create Tag
        run: |
          git config --global user.email "jt-atkins@uk.ibm.com"
          git config --global user.name "jt-atkins"
          git tag -a ${{ github.ref_name }}-RC -m "Release tag"
          git push origin ${{ github.ref }}
          
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref_name }}-RC"
          
      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-RC
          release_name: Release ${{ github.ref_name }}-RC
          body: "This is the start of a release candidate called ${{ github.ref_name }}-RC tag."
          prerelease: true
