name: EGL-Build-Pipeline
## Notes:
# A sample z/OS DBB workflow using GitHub Actions (GHA) with SSH connection
# Global vars
env:
  # SSH connection information
  DBB_Host: '"C:\Program Files\PuTTY\plink.exe" DMJTA1@WTSC47.CPOLAB.IBM.COM -pw ${{ secrets.WTSC47_PW }}' # A valid SSH account on Z. With pre-generated and tested keys in the runner.
  # Pipeline scripts on z/OS (relative to the SSH user's Home Dir in USS)
  Clone: '/u/DMJTA1/GitHubWS/scripts/git-clone-ssh.sh' # Script to clone the code from GitHub to z/OS
  DBB_Build: '/u/DMJTA1/GitHubWS/scripts/dbb-build.sh' # Script to perform the DBB build on z/OS
  UCD_Package: '/u/DMJTA1/GitHubWS/scripts/PublishUCD.sh' # Script to perform the DBB build on z/OS
  UCD_Deploy: '/u/DMJTA1/GitHubWS/scripts/DeployUCD.sh' # Script to perform the DBB build on z/OS
# "on" trigger to manually start this workflow. Can add "pull, push..." for auto trigger.
# see https://docs.github.com/en/actions/learn-github-actions/contexts
on: 
    workflow_dispatch:
    
      
jobs:
  DBB_Build_on_zOS:
    runs-on: self-hosted
    env:
        # Project related variables. GHA automatically fills in relevant repository information for values enclosed in ${{ ... }}.
        MyRepo: git@github.ibm.com:Jt-atkins/GenappML2.git # Source code repository URL (SSH)
        MyBranch: eglcobol # Branch on which to run the GHA pipeline
        MyWorkDir: /u/DMJTA1/GitHubWS/egl/Genapp_run_${{ github.run_number }} # Absolute path to directory for storing the clone and build outputs
        MyWorkSpace: /u/DMJTA1/GitHubWS/egl/Genapp_run_${{ github.run_number }}/GenappML2  # Absolute path to workspace (root) directory containing all required source directories
        UCD_AppProps: /u/DMJTA1/zAppBuild/test/Jt-atkins-dbb-zappbuild1/EGLGenappRepositoryProps.properties
        MyApplication: cics-genapp # Application directory name (relative to MyWorkSpace)
        MyHlq: DMJTA1 # High level qualifier for partitioned data sets created during the build
    steps:
      # Add step for Git Clone of EGL repo 
      # Add step for Generating COBOL from EGL 
        - name: Run PowerShell script
          run: |
            Set-Variable -name 'repository_url' -value 'git@github.ibm.com:Jt-atkins/GenappML2.git'
            Set-Variable -name 'checkout_branch' -value 'eglcobol'
            Set-Variable -name 'copy_directory' -value 'C:\rbd'
            powershell -File C:\Users\JosephTaffe-Atkins\script2.ps1 -repository_url $repository_url -checkout_branch $checkout_branch -copy_directory $copy_directory

        - name: Clone Cobol repository
          run: ${{ env.DBB_Host }} ${{ env.Clone }} ${{ env.MyRepo }} ${{ env.MyWorkDir }} ${{ env.MyWorkSpace }} ${{ env.MyBranch }}
          shell: cmd 
          
        - name: DBB Impact Build
          run: ${{ env.DBB_Host }} ${{ env.DBB_Build }} ${{ env.MyWorkDir }} ${{ env.MyWorkSpace }} ${{ env.MyApplication }} ${{ env.MyHlq }} --impactBuild --verbose
          shell: cmd 
          
        - name: Package
          run: ${{ env.DBB_Host }} ${{ env.UCD_Package }} ${{ env.MyBranch }}.${{ github.run_number }}  GeneralsBackendComponent ${{ env.MyWorkDir }} ${{ env.UCD_AppProps }}
          shell: cmd 
          
        - name: Deploy  
          run: ${{ env.DBB_Host }} ${{ env.UCD_Deploy }} General-Insurance DEV https://9.76.61.223:8443 GeneralsBackendComponent:latest Deploy
          shell: cmd 
